name: Release Builder
permissions:
  contents: read
on:
  release:
    types: [published]
jobs:
  build:
    # Only non-pre-release builds trigger a release
    if: "!github.event.release.prerelease"
    name: Python Release Builder
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.14"
    - name: Install build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build the sdist and wheel
      run: >-
        python3 -m
        build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@ba38be9e461d3875417946c167d0b5f3d385a247 # v1.14.1
