name: Release Builder
permissions:
  contents: read
on:
  release:
    types: [published]
jobs:
  build:
    # Only non-pre-release builds trigger a release
    if: "!github.event.release.prerelease"
    name: Python Release Builder
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - name: Install build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build the sdist and wheel
      run: >-
        python3 -m
        build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
