name: Snapshot Builder
permissions:
  contents: read
on:
  release:
    types: [published]
jobs:
  build:
    # Pre-release builds trigger a snapshot being created
    if: "github.event.release.prerelease"
    name: Python Snapshot Builder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.14"
    - name: Install build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build the sdist and wheel
      run: >-
        python3 -m
        build
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
