name: Snapshot Builder
permissions:
  contents: read
on:
  release:
    types: [published]
jobs:
  build:
    # Pre-release builds trigger a snapshot being created
    if: "github.event.release.prerelease"
    name: Python Snapshot Builder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: "3.14"
    - name: Install build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build the sdist and wheel
      run: >-
        python3 -m
        build
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
